# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 自动抓取

on:
 workflow_dispatch:
 schedule:
    # - cron: '*/5 * * * *'
    # 表达式生成  https://crontab.guru/
    # 每120分钟运行一次
    - cron: '*/120 * * * *'
jobs:
  Spider:
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装node
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: 启动转换服务器
      run: docker run -d --net=host --name subconverter tindy2013/subconverter
      # run: docker run -d -p 25500:25500 --name subconverter tindy2013/subconverter
    - name: 启动 clash 
      run: |
        cd utils/clash 
        chmod +x ./clash
        nohup ./clash -d . &
        cd /home/runner/work/clashpool/clashpool
    - name: 安装依赖
      run: npm i
    # - name: 升级geoip-lite数据库
    #   run: npm run updatedb
    - name: 执行任务
      run: node index.js
   
    - name: 提交更改
      run: |                 
         git config --local user.email "actions@workflows.com"
         git config --local user.name "actions@workflows"
         git add ./
         git commit -m "更新订阅链接"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
         branch: main
  CDN:
    runs-on: ubuntu-latest
    steps:
    - name: ClashCDN
      run: curl https://purge.jsdelivr.net/gh/git-wally94/clashpool@main/sub/clash.yaml
    - name: V2rayCDN   
      run: curl https://purge.jsdelivr.net/gh/git-wally94/clashpool@main/sub/v2ray.txt

